"""courses

Revision ID: 76668bdbb4de
Revises: 
Create Date: 2025-02-04 15:18:15.826670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76668bdbb4de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('criteria', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_accessed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Float(), nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prerequisites', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('learning_outcomes', sa.ARRAY(sa.String()), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'students', ['host_id'], ['id'])

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_preferences', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('language_preference', sa.String(length=10), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('points')
        batch_op.drop_column('streak_days')

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('language_preference')
        batch_op.drop_column('theme_preference')
        batch_op.drop_column('notification_preferences')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('host_id')
        batch_op.drop_column('location')
        batch_op.drop_column('capacity')
        batch_op.drop_column('type')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('learning_outcomes')
        batch_op.drop_column('prerequisites')
        batch_op.drop_column('description')
        batch_op.drop_column('thumbnail_url')

    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('last_accessed')

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_column('points')
        batch_op.drop_column('criteria')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
